import { readFileSync } from 'node:fs';
import { XMLParser } from 'fast-xml-parser';
const kml = readFileSync('/Users/johnnyzhang/extra_sport/2025-10-03 13 36 42.kml', 'utf8');
const parser = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_', trimValues: true, parseTagValue: false });
const root = parser.parse(kml);
const doc = root.kml?.Document ?? root.kml ?? {};
const pms = Array.isArray(doc.Placemark) ? doc.Placemark : (doc.Placemark ? [doc.Placemark] : []);
console.log('Placemark 数量:', pms.length);
const trackPm = pms.find((p) => p.LineString || p['gx:Track']);
console.log('轨迹 Placemark keys:', Object.keys(trackPm || {}));
console.log('LineString:', JSON.stringify(trackPm?.LineString)?.slice(0, 300));
const gxTrack = trackPm?.['gx:Track'];
console.log('gx:Track keys:', gxTrack ? Object.keys(gxTrack) : '无');
